### ISSUE TITLE
When there is unmodified src/obj file, it should not excute any rule from Makefile. It supposed to say nothing to compile.

### ISSUE THREAD

**Issue by somnathbghule** [srinu47/genmake#1]
msys@msys-Lenovo-E40-80:~/test$ make
cc -g -Wall   -c test.c 
test.c: In function ‘main’:
test.c:5:2: warning: implicit declaration of function ‘show’ [-Wimplicit-function-declaration]
  show();
  ^~~~
cc -g -Wall   -c src.c 
src.c: In function ‘show’:
src.c:6:2: warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]
  printf("show called\n");
  ^~~~~~
src.c:6:2: warning: incompatible implicit declaration of built-in function ‘printf’
src.c:6:2: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
cc  -g -Wall   ./test.o ./src.o -o test  
msys@msys-Lenovo-E40-80:~/test$ make
cc  -g -Wall   ./test.o ./src.o -o test  
msys@msys-Lenovo-E40-80:~/test$

**Comment by srinu47** [comment]
Resolved and its already merged when i have the admin rights
